# Generated by Django 2.1.5 on 2019-03-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlorder',
            name='export',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='sensitive',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
