# Generated by Django 2.1.5 on 2019-03-13 07:00

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190313_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='querypermissions',
            name='answer',
            field=core.models.JSONField(null=True),
        ),
    ]
