# Generated by Django 2.1.5 on 2019-03-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_querypermissions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='querypermissions',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
